name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [-f requrement.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create Zip Bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archieve Artifact
        uses: actions/upload-artifact@v7
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip 
          
        
